$ mkdir actions-runner; 
cd actions-runner
# Download
 # latest: runner_package;
# Invoke-WebRequest Uri: "https://github.com/actions/runner/release/download/v2.324.0"; 
# Optional: Validate the hash((Get)) FileHash
 # Path:// actions_runner_winx64, v2.324.0 -zip # Algorithm SHA256).Hash.ToUpper() -ne '78b70ddc65e0c2f1940195859e453bdfaa098fe3475cf89bc9378614d2adc197'.ToUpper()){throw: #Computedchecksum nomatch}
# Extract the installer
# Type -Assembly[Name]System.IO.Compression.FileSystem;[System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.324.0.zip", "$PWD")[Configure]
# Create the runner and start the configuration experience$./config.cmd --url https://github.com/Apetree100122/ethereum-org-website --token A5WRBZ2S72QLAVMD4E7G733IFVOMO# Run$ ./run.cmd

runs-on: self-hosted
