# Setup actions runner
steps:
  - name: Create actions-runner directory
    run: mkdir actions-runner

  - name: Change to actions-runner directory
    run: cd actions-runner

  # Download latest runner package
  # - name: Download runner
  #   run: |
  #     Invoke-WebRequest -Uri "https://github.com/actions/runner/release/download/v2.324.0"
  #     # Optional: Validate the hash
  #     # (Get-FileHash -Path actions_runner_winx64_v2.324.0.zip -Algorithm SHA256).Hash.ToUpper() -ne '78b70ddc65e0c2f1940195859e453bdfaa098fe3475cf89bc9378614d2adc197'.ToUpper() | throw

  # Extract the installer
  # - name: Extract installer
  #   run: |
  #     Add-Type -AssemblyName System.IO.Compression.FileSystem
  #     [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD/actions-runner-win-x64-2.324.0.zip", "$PWD")

  # Configure the runner
  # - name: Configure runner
  #   run: ./config.cmd --url https://github.com/Apetree100122/ethereum-org-website --token A5WRBZ2S72QLAVMD4E7G733IFVOMO

  # Start the runner
  # - name: Start runner
  #   run: ./run.cmd

runs-on: self-hosted
